- alias: Turn on kitchen light when there is movement
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2_10
    from: '0'
    to: '8'
  action:
    service: homeassistant.turn_on
    entity_id: group.hall_lights

- alias: Turn off kitchen light 10 minutes after last movement
  trigger:
    platform: state
    entity_id: sensor.aeotec_zw100_multisensor_6_burglar_2_10
    from: '8'
    to: '0'
  action:
    service: homeassistant.turn_off
    entity_id: group.hall_lights

