homeassistant:
  # Name of the location where Home Assistant is running
  name: Abernathy Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_location
  longitude: !secret longitude_location
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include customize.yaml
# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

emulated_hue:

switch:
  platform: rpi_rf
  gpio: 17
  switches:
    bedroom_outlet2:
      protocol: 1
      pulselength: 436
      code_on: 5326165
      code_off: 5326164

    bedroom_outlet1:
      protocol: 1
      pulselength: 436
      code_on: 5313877
      code_off: 5313876

    bedroom_outlet3:
      protocol: 1
      pulselength: 436
      code_on: 5329237
      code_off: 532923
group: !include groups.yaml
zwave: !include zwave_device_config.yaml

mqtt:

  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqqt_username
  password: !secret mqqt_password

light:
  - platform: lifx

automation: !include automation.yaml
scene:
  platform: lifx_cloud
  token: !secret scene_token
